name: Cargo Build & Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env: 
  CARGO_TERM_COLOR: always

jobs:
  linux-x86_64-aarch64:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          # - x86_64-unknown-linux-gnu
          # - x86_64-unknown-linux-musl
          # - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          # - aarch64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Setup Zig
        if: matrix.target == 'aarch64-apple-darwin'
        uses: Rogue-King/setup-zig@v1.2.0
        with:
          version: latest

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
          
      - name: Install cross compilation tools
        run: |
          sudo apt-get update 

          # Install linkers and cross-compilation tools
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu
          elif [[ "${{ matrix.target }}" == "aarch64-unknown-linux-musl" ]]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu musl-tools
          elif [[ "${{ matrix.target }}" == "x86_64-unknown-linux-musl" ]]; then
            sudo apt-get install -y musl-tools
          fi

      - name: Configure linkers
        run: |
          mkdir -p ~/.cargo
          cat >> ~/.cargo/config.toml << EOF
          [target.aarch64-unknown-linux-gnu]
          linker = "aarch64-linux-gnu-gcc"
          
          [target.aarch64-unknown-linux-musl]
          linker = "aarch64-linux-gnu-gcc"
          EOF

      - name: Install cargo-zigbuild
        if: matrix.target == 'aarch64-apple-darwin'
        run: cargo install --locked cargo-zigbuild

    
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: |
          if [[ "${{ matrix.target }}" == "aarch64-apple-darwin" ]]; then
            cargo zigbuild --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi